### ISSUE TITLE
Widget Layout Problem

### ISSUE THREAD

**Issue by as-shahriar** [sarkerjr/Coronavirus-Updates-Bangladesh#1]
When App gets large number in update, it goes to next line and extends the size of the layer.
You can set 'Notun' in new line line 'Mot'.  <br>
![94762902_263882428074666_622415532276056064_n](https://user-images.githubusercontent.com/34039975/80419501-1218b780-88fb-11ea-81e1-9efc9ef9750d.jpg)

**Comment by sarkerjr** [comment]
Fixed with minimum width enhancement.
