### ISSUE TITLE
Add 'Loading' in widget

### ISSUE THREAD

**Issue by as-shahriar** [sarkerjr/Coronavirus-Updates-Bangladesh#2]
When User tap to update the widget, set the numbers to 'Loading' and if loaded successfully show the numbers else Error.

**Comment by ghost** [comment]
Add an icon while refreshing that will show it's refreshing or after refresh you can add a simple line like " updated 0 or 1 seconds ago"

**Comment by sarkerjr** [comment]
Roger that!
