### ISSUE TITLE
Loading Stuck If no Internet Connection

### ISSUE THREAD

**Issue by as-shahriar** [sarkerjr/Coronavirus-Updates-Bangladesh#3]
When I install the app with no internet connection, It shows Loading, but if I tap to reload it isn't working, still shows Loading. 
<br><br>
![Loading](https://user-images.githubusercontent.com/34039975/80472769-fe0a9f80-8966-11ea-9e13-4b7438b02f89.jpg)

**Comment by sarkerjr** [comment]
Done dana Done!
